codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default: false
      server-mariadb:
        target: auto
        threshold: 0.5%
        flags:
          - server-mariadb
    patch:
      default: false
      server-mariadb:
        target: 85%
        threshold: 0%
        only_pulls: true
        if_ci_failed: ignore
        flags:
          - server-mariadb

comment:
  layout: "diff, flags"
  require_changes: true

flags:
  server-mariadb:
    paths:
      - "**/*.py"
    carryforward: true
  server-postgres:
    paths:
      - "**/*.py"
    carryforward: true
  ui-tests:
    paths:
      - "**/*.js"
    carryforward: true
  server-ui:
    paths:
      - "**/*.py"
    carryforward: true
