name: UI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ develop ]

concurrency:
  group: ui-develop-${{ github.event_name }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      build: ${{ steps.check-build.outputs.build }}

    strategy:
      fail-fast: false
      matrix:
       # Make sure you modify coverage submission file list if changing this
       container: [1, 2, 3]

    name: UI Tests (Cypress)

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MARIADB_ROOT_PASSWORD: travis
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check for valid Python & Merge Conflicts
        run: |
          python -m compileall -f "${GITHUB_WORKSPACE}"
          if grep -lr --exclude-dir=node_modules "^<<<<<<< " "${GITHUB_WORKSPACE}"
              then echo "Found merge conflicts"
              exit 1
          fi

      - name: Check if build should be run
        id: check-build
        run: |
          python "${GITHUB_WORKSPACE}/.github/helper/roulette.py"
        env:
          TYPE: "ui"
          PR_NUMBER: ${{ github.event.number }}
          REPO_NAME: ${{ github.repository }}

      - uses: actions/setup-node@v3
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        with:
          node-version: 16
          check-latest: true

      - name: Add to Hosts
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        run: |
          echo "127.0.0.1 test_site" | sudo tee -a /etc/hosts
          echo "127.0.0.1 test_site_producer" | sudo tee -a /etc/hosts

      - name: Cache pip
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt', '**/pyproject.toml', '**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Cache node modules
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Get yarn cache directory path
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache cypress binary
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cypress-
          restore-keys: |
            ${{ runner.os }}-cypress-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        run: |
          bash ${GITHUB_WORKSPACE}/.github/helper/install_dependencies.sh
          bash ${GITHUB_WORKSPACE}/.github/helper/install.sh
        env:
          BEFORE: ${{ env.GITHUB_EVENT_PATH.before }}
          AFTER: ${{ env.GITHUB_EVENT_PATH.after }}
          TYPE: ui
          DB: mariadb

      - name: Instrument Source Code
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        run: cd ~/frappe-bench/apps/frappe/ && npx nyc instrument -x 'frappe/public/dist/**' -x 'frappe/public/js/lib/**' -x '**/*.bundle.js' --compact=false --in-place frappe

      - name: Build
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        run: cd ~/frappe-bench/ && bench build --apps frappe

      - name: Site Setup
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        run: cd ~/frappe-bench/ && bench --site test_site execute frappe.utils.install.complete_setup_wizard

      - name: UI Tests
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        run: cd ~/frappe-bench/ && bench --site test_site run-ui-tests frappe --with-coverage --headless --parallel --ci-build-id $GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT
        env:
          CYPRESS_RECORD_KEY: 4a48f41c-11b3-425b-aa88-c58048fa69eb

      - name: Stop server and wait for coverage file
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        run: |
          ps -ef | grep "[f]rappe serve" | awk '{print $2}' | xargs kill -s SIGINT
          sleep 5
          ( tail -f /home/runner/frappe-bench/sites/coverage.xml & ) | grep -q "\/coverage"

      - name: Upload JS coverage data
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-js-${{ matrix.container }}
          path: /home/runner/frappe-bench/apps/frappe/.cypress-coverage/clover.xml

      - name: Upload python coverage data
        if: ${{ steps.check-build.outputs.build == 'strawberry' }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-py-${{ matrix.container }}
          path: /home/runner/frappe-bench/sites/coverage.xml

      - name: Show bench output
        if: ${{ always() }}
        run: cat ~/frappe-bench/bench_start.log || true


  coverage:
    name: Coverage Wrap Up
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download artifacts
        if: ${{ needs.test.outputs.build == 'strawberry' }}
        uses: actions/download-artifact@v3

      - name: Upload python coverage data
        if: ${{ needs.test.outputs.build == 'strawberry' }}
        uses: codecov/codecov-action@v3
        with:
          name: UIBackend
          fail_ci_if_error: true
          verbose: true
          files: ./coverage-py-1/coverage.xml,./coverage-py-2/coverage.xml,./coverage-py-3/coverage.xml
          flags: server-ui

      - name: Upload JS coverage data
        if: ${{ needs.test.outputs.build == 'strawberry' }}
        uses: codecov/codecov-action@v3
        with:
          name: Cypress
          fail_ci_if_error: true
          files: ./coverage-js-1/clover.xml,./coverage-js-2/clover.xml,./coverage-js-3/clover.xml
          verbose: true
          flags: ui-tests
